---
title: "Homework5"
author: "Paulina Han"
date: "2021/11/13"
output: github_document
---
```{r}
library(tidyverse)
library(rvest)
library(httr)

```


```{r}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

# Problem 1

```{r}
# read the data
url_1 = "https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv"

df = read_csv(url(url_1))

#create a city_state variable
df = 
  df %>% 
  mutate(
    city = as.factor(city),
    city_state = as.factor(paste(city, state, sep=",")))%>% 
  filter(city_state != "Tulsa_AL")

#create count of homicide
df = 
  df %>% 
  group_by(city) %>% 
  mutate(count = n()) 

#count unsolved cases
unsolved = df %>% 
  filter(disposition %in% c("Closed without arrest", "Open/No arrest")) %>% 
  group_by(city) %>% 
  summarize(unsolve_count = n()) %>% 
  distinct()

#join
df = left_join(df,unsolved,by ="city") 
```

This `df ` data set is recording the  data included the location of the killing, whether an arrest was made and, in most cases, basic demographic information about each victim. There are `r nrow(df)` observations in the datt set and `r ncol(df)` variables in the data set.

```{r}
#creat a new data set
df_2 = df %>% 
  select(city_state,count,unsolve_count) %>% 
  distinct()

#prop.test ? how to estimate?
bal_prop = prop.test(df_2 %>% filter(city_state == "Baltimore,MD") %>%  pull(unsolve_count),
  df_2 %>% filter(city_state == "Baltimore,MD") %>%  pull(count))
bal_prop %>% broom::tidy()

#all cities
results_df = 
  df_2 %>% 
  mutate(
    prop_tests = map2(.x = unsolve_count, .y = count, ~prop.test(x = .x, n = .y)),
    tidy_tests = map(.x = prop_tests, ~broom::tidy(.x))
  ) %>% 
  select(-prop_tests) %>% 
  unnest(tidy_tests) %>% 
  select(city_state, estimate, conf.low, conf.high)#why always have city

#plot why cannot reorder: must ungroup first
results_df %>% 
  ungroup() %>% 
  mutate(city = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city, y = estimate)) +
  geom_point() + 
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  labs(
    title = "prop.test of unsolve cases",
    x = "city",
    y = "unsolve cases",
    ) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```


# Problem 2

```{r}

```

